# Generated by Django 6.0.7 on 2026-08-02 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField(db_index=True)),
                ('first_post_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='equibase', max_length=40)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'race days',
                'ordering': ['-race_date', 'track__code'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('entries', 'Entries'), ('results', 'Results'), ('live', 'Live'), ('tracks', 'Tracks')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('source', models.CharField(max_length=40)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('track_codes', models.JSONField(blank=True, default=list)),
                ('races_upserted', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(default='USA', max_length=3)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_number', models.PositiveSmallIntegerField()),
                ('race_name', models.CharField(blank=True, max_length=255)),
                ('race_type', models.CharField(blank=True, max_length=80)),
                ('distance', models.CharField(blank=True, help_text='e.g. 1 1/16M', max_length=40)),
                ('distance_furlongs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('surface', models.CharField(choices=[('D', 'Dirt'), ('T', 'Turf'), ('S', 'Synthetic'), ('U', 'Unknown')], default='U', max_length=1)),
                ('purse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('post_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('next', 'Next'), ('running', 'Running'), ('official', 'Official'), ('cancelled', 'Cancelled'), ('scratched', 'Scratched')], db_index=True, default='scheduled', max_length=20)),
                ('conditions', models.TextField(blank=True)),
                ('video_replay_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='racing.raceday')),
            ],
            options={
                'ordering': ['race_day__race_date', 'race_number'],
                'unique_together': {('race_day', 'race_number')},
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_time', models.CharField(blank=True, max_length=32)),
                ('official_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='equibase', max_length=40)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='racing.race')),
            ],
        ),
        migrations.AddField(
            model_name='raceday',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_days', to='racing.track'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('W', 'Win / Ganador'), ('P', 'Place / Place'), ('S', 'Show / Show'), ('EXA', 'Exacta'), ('TRI', 'Trifecta'), ('SUPER', 'Superfecta'), ('DD', 'Daily Double'), ('P3', 'Pick 3'), ('P4', 'Pick 4'), ('P5', 'Pick 5'), ('P6', 'Pick 6')], max_length=10)),
                ('combination', models.CharField(blank=True, help_text='e.g. 9-2 or 9-2-7', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_wager', models.DecimalField(decimal_places=2, default=2.0, max_digits=8)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='racing.race')),
            ],
            options={
                'ordering': ['bet_type'],
                'unique_together': {('race', 'bet_type', 'combination')},
            },
        ),
        migrations.CreateModel(
            name='Finisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('program_number', models.CharField(max_length=8)),
                ('horse_name', models.CharField(blank=True, max_length=120)),
                ('jockey', models.CharField(blank=True, max_length=120)),
                ('trainer', models.CharField(blank=True, max_length=120)),
                ('win_payoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('place_payoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('show_payoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishers', to='racing.raceresult')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('result', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(max_length=8)),
                ('horse_name', models.CharField(max_length=120)),
                ('jockey', models.CharField(blank=True, max_length=120)),
                ('trainer', models.CharField(blank=True, max_length=120)),
                ('morning_line_odds', models.CharField(blank=True, max_length=20)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scratched', models.BooleanField(default=False)),
                ('post_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='racing.race')),
            ],
            options={
                'ordering': ['post_position', 'program_number'],
                'unique_together': {('race', 'program_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='raceday',
            unique_together={('track', 'race_date')},
        ),
        migrations.CreateModel(
            name='VipPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_window', models.CharField(choices=[('morning', 'Mañana'), ('last_hour', 'Última Hora')], max_length=20)),
                ('selections', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_picks', to='racing.race')),
            ],
            options={
                'ordering': ['pick_window'],
                'unique_together': {('race', 'pick_window')},
            },
        ),
    ]
