# Generated by Django 6.0.7 on 2026-08-02 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='job_type',
            field=models.CharField(choices=[('entries', 'Entries'), ('results', 'Results'), ('live', 'Live'), ('near_post', 'Near Post'), ('tracks', 'Tracks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vippick',
            name='pick_window',
            field=models.CharField(choices=[('morning', 'Mañana / Our Picks'), ('mtp5', '5 MTP'), ('last_hour', 'Última Hora')], max_length=20),
        ),
        migrations.CreateModel(
            name='OddsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(max_length=8)),
                ('morning_odds', models.CharField(blank=True, max_length=20)),
                ('mtp5_odds', models.CharField(blank=True, max_length=20)),
                ('morning_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mtp5_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, help_text='mtp5_decimal - morning_decimal (negative = shortened)', max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('shortened', 'Shortened'), ('drifted', 'Drifted'), ('unchanged', 'Unchanged')], default='unchanged', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_movements', to='racing.race')),
            ],
            options={
                'ordering': ['program_number'],
                'unique_together': {('race', 'program_number')},
            },
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(max_length=8)),
                ('odds', models.CharField(max_length=20)),
                ('odds_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mtp_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Null = morning/open line; 5 = five minutes to post', null=True)),
                ('source', models.CharField(default='demo', max_length=40)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='racing.race')),
            ],
            options={
                'ordering': ['program_number', 'mtp_minutes'],
                'indexes': [models.Index(fields=['race', 'mtp_minutes'], name='racing_odds_race_id_17fdad_idx')],
            },
        ),
    ]
