# Generated by Django 6.0.7 on 2026-08-02 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_alter_scrapejob_job_type_alter_vippick_pick_window_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceTipSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selections', models.JSONField(blank=True, default=list)),
                ('max_speed', models.JSONField(blank=True, default=list)),
                ('first_class', models.JSONField(blank=True, default=list)),
                ('max_pace', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='demo', max_length=40)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_sheet', to='racing.race')),
            ],
        ),
    ]
