# Generated by Django 6.0.7 on 2026-08-02 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_racetipsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finisher',
            options={'ordering': ['position'], 'verbose_name': 'Llegada', 'verbose_name_plural': 'Llegada'},
        ),
        migrations.AlterModelOptions(
            name='oddsmovement',
            options={'ordering': ['program_number'], 'verbose_name': 'Movimiento de cuotas', 'verbose_name_plural': 'Movimientos de cuotas'},
        ),
        migrations.AlterModelOptions(
            name='oddssnapshot',
            options={'ordering': ['program_number', 'mtp_minutes'], 'verbose_name': 'Snapshot de cuotas', 'verbose_name_plural': 'Snapshots de cuotas'},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['bet_type'], 'verbose_name': 'Dividendo', 'verbose_name_plural': 'Dividendos'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['race_day__race_date', 'race_number'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='raceday',
            options={'ordering': ['-race_date', 'track__code'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='raceresult',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterModelOptions(
            name='racetipsheet',
            options={'verbose_name': 'Hoja de consejos', 'verbose_name_plural': 'Hojas de consejos'},
        ),
        migrations.AlterModelOptions(
            name='runner',
            options={'ordering': ['post_position', 'program_number'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='scrapejob',
            options={'ordering': ['-started_at'], 'verbose_name': 'Job de scrape', 'verbose_name_plural': 'Jobs de scrape'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name'], 'verbose_name': 'Hipódromo', 'verbose_name_plural': 'Hipódromos'},
        ),
        migrations.AlterModelOptions(
            name='vippick',
            options={'ordering': ['pick_window'], 'verbose_name': 'Pick VIP', 'verbose_name_plural': 'Picks VIP'},
        ),
        migrations.AlterField(
            model_name='finisher',
            name='horse_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Caballo'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='jockey',
            field=models.CharField(blank=True, max_length=120, verbose_name='Jinete'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='place_payoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pago place'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='program_number',
            field=models.CharField(max_length=8, verbose_name='Nº programa'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishers', to='racing.raceresult', verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='show_payoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pago show'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='trainer',
            field=models.CharField(blank=True, max_length=120, verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='finisher',
            name='win_payoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pago win'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='computed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Calculado'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='delta',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='mtp5_decimal - morning_decimal (negativo = acortó)', max_digits=10, null=True, verbose_name='Delta'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='direction',
            field=models.CharField(choices=[('shortened', 'Acortó'), ('drifted', 'Alargó'), ('unchanged', 'Sin cambio')], default='unchanged', max_length=20, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='morning_decimal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Decimal mañana'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='morning_odds',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cuota mañana'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='mtp5_decimal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Decimal 5 MTP'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='mtp5_odds',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cuota 5 MTP'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='program_number',
            field=models.CharField(max_length=8, verbose_name='Nº programa'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_movements', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Capturado'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='mtp_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vacío = línea de mañana; 5 = cinco minutos a post', null=True, verbose_name='Minutos a post'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='odds',
            field=models.CharField(max_length=20, verbose_name='Cuota'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='odds_decimal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cuota decimal'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='program_number',
            field=models.CharField(max_length=8, verbose_name='Nº programa'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='source',
            field=models.CharField(default='demo', max_length=40, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='base_wager',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8, verbose_name='Base'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bet_type',
            field=models.CharField(choices=[('W', 'Win / Ganador'), ('P', 'Place'), ('S', 'Show'), ('EXA', 'Exacta'), ('TRI', 'Trifecta'), ('SUPER', 'Superfecta'), ('DD', 'Daily Double'), ('P3', 'Pick 3'), ('P4', 'Pick 4'), ('P5', 'Pick 5'), ('P6', 'Pick 6')], max_length=10, verbose_name='Tipo de apuesta'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='combination',
            field=models.CharField(blank=True, help_text='ej. 9-2 o 9-2-7', max_length=64, verbose_name='Combinación'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='race',
            name='conditions',
            field=models.TextField(blank=True, verbose_name='Condiciones'),
        ),
        migrations.AlterField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(blank=True, help_text='ej. 1 1/16M', max_length=40, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance_furlongs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Furlongs'),
        ),
        migrations.AlterField(
            model_name='race',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ID externo'),
        ),
        migrations.AlterField(
            model_name='race',
            name='post_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Hora de post'),
        ),
        migrations.AlterField(
            model_name='race',
            name='purse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bolsa'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='racing.raceday', verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_number',
            field=models.PositiveSmallIntegerField(verbose_name='Nº carrera'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='race',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload bruto'),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('next', 'Siguiente'), ('running', 'En curso'), ('official', 'Oficial'), ('cancelled', 'Cancelada'), ('scratched', 'Anulada')], db_index=True, default='scheduled', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='race',
            name='surface',
            field=models.CharField(choices=[('D', 'Dirt'), ('T', 'Turf'), ('S', 'Sintético'), ('U', 'Desconocido')], default='U', max_length=1, verbose_name='Pista'),
        ),
        migrations.AlterField(
            model_name='race',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='race',
            name='video_replay_url',
            field=models.URLField(blank=True, verbose_name='Replay'),
        ),
        migrations.AlterField(
            model_name='raceday',
            name='first_post_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primer post'),
        ),
        migrations.AlterField(
            model_name='raceday',
            name='race_date',
            field=models.DateField(db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='raceday',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scrapeado'),
        ),
        migrations.AlterField(
            model_name='raceday',
            name='source',
            field=models.CharField(default='equibase', max_length=40, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='raceday',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_days', to='racing.track', verbose_name='Hipódromo'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='official_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oficializado'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='scraped_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Scrapeado'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='source',
            field=models.CharField(default='equibase', max_length=40, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='winning_time',
            field=models.CharField(blank=True, max_length=32, verbose_name='Tiempo ganador'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='first_class',
            field=models.JSONField(blank=True, default=list, verbose_name='Primera clase'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='max_pace',
            field=models.JSONField(blank=True, default=list, verbose_name='Ritmo máximo'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='max_speed',
            field=models.JSONField(blank=True, default=list, verbose_name='Velocidad máxima'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_sheet', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='selections',
            field=models.JSONField(blank=True, default=list, verbose_name='Selecciones'),
        ),
        migrations.AlterField(
            model_name='racetipsheet',
            name='source',
            field=models.CharField(default='demo', max_length=40, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='horse_name',
            field=models.CharField(max_length=120, verbose_name='Caballo'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='jockey',
            field=models.CharField(blank=True, max_length=120, verbose_name='Jinete'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='morning_line_odds',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cuota mañana'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='post_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='program_number',
            field=models.CharField(max_length=8, verbose_name='Nº programa'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='scratched',
            field=models.BooleanField(default=False, verbose_name='Retirado'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='trainer',
            field=models.CharField(blank=True, max_length=120, verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='job_type',
            field=models.CharField(choices=[('entries', 'Entries'), ('results', 'Resultados'), ('live', 'En vivo'), ('near_post', 'Cerca del post'), ('tracks', 'Hipódromos')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='races_upserted',
            field=models.PositiveIntegerField(default=0, verbose_name='Carreras actualizadas'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='source',
            field=models.CharField(max_length=40, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('running', 'En ejecución'), ('success', 'Éxito'), ('partial', 'Parcial'), ('failed', 'Fallido')], default='running', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha objetivo'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='track_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Códigos de pista'),
        ),
        migrations.AlterField(
            model_name='track',
            name='code',
            field=models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='track',
            name='country',
            field=models.CharField(default='USA', max_length=3, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='state',
            field=models.CharField(blank=True, max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='track',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64, verbose_name='Zona horaria'),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='track',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='vippick',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='vippick',
            name='pick_window',
            field=models.CharField(choices=[('morning', 'Mañana / Our Picks'), ('mtp5', '5 MTP'), ('last_hour', 'Última Hora')], max_length=20, verbose_name='Ventana'),
        ),
        migrations.AlterField(
            model_name='vippick',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='vippick',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_picks', to='racing.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='vippick',
            name='selections',
            field=models.JSONField(default=list, verbose_name='Selecciones'),
        ),
    ]
