# Generated by Django 6.0.7 on 2026-08-02 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralattribution',
            options={'ordering': ['-created_at'], 'verbose_name': 'Atribución de referido', 'verbose_name_plural': 'Atribuciones de referido'},
        ),
        migrations.AlterModelOptions(
            name='referralprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perfil de referido', 'verbose_name_plural': 'Perfiles de referido'},
        ),
        migrations.AlterModelOptions(
            name='rewardledger',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento de recompensa', 'verbose_name_plural': 'Ledger de recompensas'},
        ),
        migrations.AlterField(
            model_name='referralattribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='referralattribution',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Calificado'),
        ),
        migrations.AlterField(
            model_name='referralattribution',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='referrals.referralprofile', verbose_name='Referido'),
        ),
        migrations.AlterField(
            model_name='referralattribution',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='referrals.referralprofile', verbose_name='Referidor'),
        ),
        migrations.AlterField(
            model_name='referralattribution',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recompensado'),
        ),
        migrations.AlterField(
            model_name='referralattribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('qualified', 'Calificado'), ('rewarded', 'Recompensado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='credits',
            field=models.PositiveIntegerField(default=0, verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='device_id',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ID de dispositivo'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='referral_code',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Código de referido'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='vip_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Días VIP'),
        ),
        migrations.AlterField(
            model_name='rewardledger',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='rewardledger',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='rewardledger',
            name='kind',
            field=models.CharField(choices=[('credit', 'Créditos'), ('vip_days', 'Días VIP')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='rewardledger',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='rewardledger',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='referrals.referralprofile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='rewardledger',
            name='reason',
            field=models.CharField(max_length=120, verbose_name='Motivo'),
        ),
    ]
