# Generated by Django 6.0.7 on 2026-08-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrega webhook', 'verbose_name_plural': 'Entregas webhook'},
        ),
        migrations.AlterModelOptions(
            name='webhookendpoint',
            options={'ordering': ['name'], 'verbose_name': 'Endpoint webhook', 'verbose_name_plural': 'Endpoints webhook'},
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intentos'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='event_type',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo reintento'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='response_body',
            field=models.TextField(blank=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Éxito'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Código HTTP'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de evento suscritos; vacío = todos', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(help_text='Secreto HMAC-SHA256 para la cabecera X-Signature', max_length=128, verbose_name='Secreto'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
